import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgDir = join(__dirname, '..', 'node_modules', '@material-symbols', 'svg-400', 'outlined');

const ICONS = [
  'add', 'close', 'delete', 'edit', 'menu', 'arrow_back', 'search',
  'filter_list', 'calendar_month', 'chevron_left', 'chevron_right',
  'location_on', 'photo_camera', 'attach_file', 'download', 'upload',
  'check_circle', 'warning', 'error', 'info', 'person', 'group', 'groups',
  'account_circle', 'settings', 'dashboard', 'folder', 'receipt_long',
  'payments', 'account_balance_wallet', 'trending_up', 'trending_down',
  'dark_mode', 'light_mode', 'logout', 'more_vert', 'expand_circle_down',
  'expand_circle_up', 'home', 'description', 'insert_chart', 'apartment',
  'flag', 'notifications', 'refresh', 'save', 'star', 'task_alt',
  'schedule', 'sync', 'print', 'share', 'image', 'camera', 'badge',
  'category', 'credit_card', 'my_location', 'north_east', 'south_east',
  'inventory_2', 'summarize', 'checklist', 'sunny', 'construction',
  'sentiment_dissatisfied', 'timeline', 'today', 'swap_horiz',
  'wallet', 'currency_rupee',
];

function parseSvg(text) {
  const viewBoxMatch = text.match(/viewBox="([^"]+)"/);
  const innerMatch = text.match(/<svg[^>]*>([\s\S]*)<\/svg>/);
  return {
    viewBox: viewBoxMatch ? viewBoxMatch[1] : '0 -960 960 960',
    inner: innerMatch ? innerMatch[1].trim() : '',
  };
}

const data = {};
const missing = [];

for (const name of ICONS) {
  const outlinePath = join(pkgDir, `${name}.svg`);
  const fillPath = join(pkgDir, `${name}-fill.svg`);
  try {
    const outlineSvg = readFileSync(outlinePath, 'utf-8');
    const outline = parseSvg(outlineSvg);
    let filled;
    try {
      const fillSvg = readFileSync(fillPath, 'utf-8');
      filled = parseSvg(fillSvg).inner;
    } catch {
      filled = undefined;
    }
    data[name] = {
      viewBox: outline.viewBox,
      outline: outline.inner,
      ...(filled ? { filled } : {}),
    };
  } catch {
    missing.push(name);
  }
}

if (missing.length) {
  console.error('Missing icons:', missing.join(', '));
}

const out = `// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
export interface IconEntry {
  viewBox: string;
  outline: string;
  filled?: string;
}

export const ICON_DATA: Record<string, IconEntry> = ${JSON.stringify(data, null, 2)};
`;

writeFileSync(join(__dirname, '..', 'src', 'lib', 'icon-data.ts'), out);
console.log(`Generated ${Object.keys(data).length} icons, ${missing.length} missing.`);
